<?php

use Illuminate\Database\Seeder;

class BeritasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $berita = [['Kegiatan Buka Puasa Bersama “Ramadhan Kareem”',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-05-13-at-12_09_16/WhatsApp-Image-2019-05-13-at-12_09_16-1207072845.jpeg',
        'nan', 'Anna', '14 Mei 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Jakarta, Jumat 10 Mei 2019 UKM IKM Nusantara diwakili Ketua Umum Hj. Chandra Manggih Rahayu bersama Ibu Nurhaeda Burhan dan Ibu Doktor Padlia selaku Dewan Pembina UKM IKM Nusantara serta Srikandi UIN Jawa Barat Ibu Fika mendapat undangan dari Pemerintah Provinsi Sulawesi Barat untuk silaturrahim dan buka puasa bersama Bapak Gubernur,dan Masyarakat Sulawesi Barat Perantauan se-Jabodetabek bertempat di Restoran Pulau Dua Senayan Jakarta. Setelah berbuka puasa ada kegiatan doa bersama dan ramah tamah setelah Iftar dan sholat maghrib berjamaah dengan Bapak Gubernur dan jajarannya yakni Pemerintahan Daerah, Bapak DirJen KKP Zulfikar Muchtar , Bapak Rektor Univ Mulawarman Kalimantan Timur dan masyarakat Sulbar , harapan dalam silaturrahin ini UKM IKM Nusantara bisa membangun sinergi dan harmonisasi hubungan yang positif antara Pemerintah Provinsi Sulawesi Barat\ndan masyarakat . #Iftar#UIN#pemdasulbar#sulbar#gubernursubar#umkm#perekonomianmaju#indonesiahebat'],
       ['Kegiatan Narasumber Ibu Ketua Umum UKM IKM Nusantara',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-04-26-at-16_26_26/WhatsApp-Image-2019-04-26-at-16_26_26-17810261.jpeg',
        'nan', 'Anna', '14 Mei 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Jakarta, Kamis 25 April 2019 Ketua Umum UKM IKM Nusantara Ibu Hj. Chandra Manggih Rahayu berkesempatan diundang sebagai Narasumber dalam pelaksanaan kegiatan Bimbingan Pemantapan Pendamping Kelompok Usaha Bersama (KUBE) Angkatan I 2019 di Hotel Aston Bekasi Jawa Barat oleh Direktorat Penanganan Fakir Miskin Kementerian Sosial RI, didampingi Bapak Warsito selaku Dewan Pembina dan Rian Darmawan Ketua Kesekretariatan UKM IKM Nusantara. Kegiatan Bimbingan Pemantapan Pendamping Kelompok Usaha Bersama(KUBE) di pimpin langsung oleh Direktur Penanganan Fakir Miskin Wilayah I Bapak A.M Asnandar bersama Ibu Endang. Acara dan kegiatan ini di hadiri kurang lebih 500peserta Para Pendamping kelompok usaha bersama (kube) dari berbagai provinsi.\nKegiatan Bimbingan Pemantapan Pendamping Kelompok Usaha Bersama(KUBE) mengambil Tema “Kerja Cerdas, Keras dan Tuntas untuk mensejahterahkan Masyarakat Miskin” sesuai dengan Visi Misi dan Program Kerja UKM IKM Nusantara untuk mensejahterakan para pelaku Usaha Mikro,Kecil,Menengah yang membutuhkan bantuan serta dukungan dari Pemerintah. Ibu Ketum menyampaikan kepada Bapak Direktur A.M Asnandar semoga ini menjadi langkah konkrit kita bersama untuk mensejahterahkan masyarakat luas tidak hanya sekedar wacana dan angan angan tapi bisa diwujudkan bersama sama. Ibu Chandra juga mengajak para peserta untuk bisa bergabung dan menjadi Anggota UKM IKM Nusantara..\nDiakhir pembicara Ibu Ketum memberikan brosur permodalan dari kebijakan UKM IKM Nusantara dan Profile UKM IKM Nusantara kepada Bapak A.M Asnandar untuk bisa merdeka Maju dan Kaya di Negeri sendiri.\nSemoga organisasi UKM IKM Nusantara bisa menjaga amanah ini dengan baik dan menjadi Wadah untuk para pelaku Usaha Kecil Menengah dan Industri Kecil Menengah untuk bisa memperjuangkan masyarakat kecil .\nSalam Nusantara\nSalam Semangat'],
       ['Audiensi UKM IKM Nusantara bersama Pemprov DKI Jakarta',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-04-26-at-11_35_13/WhatsApp-Image-2019-04-26-at-11_35_13-2443590006.jpeg',
        'nan', 'Anna', '14 Mei 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Jakarta, Kamis 25 April 2019 Perkumpulan UKM IKM Nusantara bersama Ketua Umum Ibu Hj. Chandra Manggih Rahayu didampingi Bapak Ais dan Ibu Santi Mia Sipan selaku Dewan Pengurus UIN, Yuda Aji Bawono Ketua harian dan para pelaku Anggota UKM IKM Nusantara antara lain Ibu Sri achriani, Ibu Nurhayah, Ibu Juliana,Ibu Eka Wahyuni, Ibu Lindawaty, Bapak Ikhwan Susetiyo dan Ibu Eka saukah diterima beraudiensi di Biro Perekonomian Setda Provinsi DKI Jakarta Disposisi Bapak Gubernur Pemprov DKI. Audiensi di pimpin oleh Ibu Sri Haryati Selaku Kepala Biro Perekonomian SetDa Pemprov DKI Jakarta serta beberapa Undangan yg hadir yakni Kusuma Wijayanto dari Pasar Jaya, Ied Sabila Diskominfo, Sugiyanto Dinas KUKMP, Sumarno Pasar Jaya'],
       ['Pembahasan Draft Nota Kesepahaman UKM IKM Nusantara bersama Direktorat Penanganan Fakir Miskin Kementerian Sosial RI',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-04-24-at-12_06_44/WhatsApp-Image-2019-04-24-at-12_06_44-738413249.jpeg',
        'nan', 'Anna', '13 Mei 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Jakarta, Selasa 23 April 2019 Dengan penuh rasa syukur Organisasi UKM IKM Nusantara bersama Ketua Umum Ibu Hj. Chandra Manggih Rahayu yang didampingi oleh Bapak Ryo dan Bapak Ais selaku Dewan Pengurus UIN, Yuda Aji Bawono Ketua Harian, Rian Dharmawan selaku Ketua Kesekretariatan, Ibu Santi Mia Sipan Ketua Komunitas WISE dan Ibu Dra. Amie Sukadji diterima dengan baik di direktorat Penanganan Fakir Miskin Kementerian Sosial RI yang dimana dalam hal ini organisasi UKM IKM Nusantara diundang untuk membahas untuk penyusunan draft Nota Kesepahaman. Penyusunan dan pembahasan nota kesepahaman di pimpin oleh Bapak M.O.Royani selaku Sekretaris Ditjen PFM, Bapak Bhakti Nusantara Kabiro Hukum, Bapak Wisnu Biro Hukum, Ibu Anisah Perancang Peraturan perundang undangan beserta Jajarannya.'],
       ['AUDIENSI UKM IKM PROV SUMATERA SELATAN DI DINAS PERINDUSTRIAN',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-04-02-at-14_40_07/WhatsApp-Image-2019-04-02-at-14_40_07-3379954108.jpeg',
        'nan', 'Anna', '2 April 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Palembang, Rabu 20 Maret 2019 Ketua Wilayah Bapak Nahnu serta Pengurus UKM IKM Nusantara Provinsi Sumatera Selatan diterima audiensi bersama Kepala Dinas Perindustrian dan jajaran pengurus para Kepala berita. Kepala Dinas Perindustrian menyambut baik keberadaan Organisasi UKM IKM Nusantara di provinsi Sumatera Selatan . Beliau juga menyampaikan apabila UKM IKM Nusantara ingin menyelenggarakan kegiatan expo Sriwijaya Ukm- Ikm Nusantara Dinas Perindustrian harus dilibatkan dan pelatihan para pelaku UKM IKM Nusantara, Dinas Perindustrian akan di undang. Bapak Nahnu menyampaikan ingin memberikan Sosialisasi perizinan kepada pelaku usaha UKM IKM di SumSel.Bapak Nahnu ingin beraudensi dengan Gubernur Sumatera Selatan agar memaksimalkan kegiatan Ukm- Ikm Nusantara secara kongkrit/nyata dan ada tindaklanjut ke pihak hotel. Bapak Nahnu serta para pengurus UKM IKM Nusantara prov Sumsel membangun “Rumah Kreatif” yang sudah di bentuk di Sumsel atas inisiatif dan inovatif untuk para pelaku UKM IKM Nusantara di Provinsi SumSel. Ketua Wilayah Bapah Nahnu mengharapkan Ukm-ikm Nusantara bukan hanya menggarap berita kuliner tetapi juga melibatkan kerajinan handycraft dll yang bisa bersinergi dengan Hotel di Sumatera Selatan. berita TTG Dinas Perindistrian menyampaikan juga untuk melibatkan pengrajin tenun dan songket agar hasilnya lebih maksimal. Semoga Ketua Wilayah Provinsi Sumatera Selatan serta para pengurusnya selalu membuat gebrakan inovatif yang bisa memacu Ketua Wilayah Provinsi lainnya ikut memajukan Usaha para Pelaku UKM IKM di Nusantara ini sesuai keinginan dan harapan Ketua Umum UKM IKM Nusantara Hj.Chandra Manggih Rahayu.'],
       ['AUDIENSI KANTOR WALIKOTA ADM JAKARTA TIMUR',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-04-02-at-14_38_38/WhatsApp-Image-2019-04-02-at-14_38_38-2256995784.jpeg',
        'nan', 'Anna', '2 April 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Jakarta, Rabu 20 Maret 2019 Pengurus UKM IKM Nusantara diterima beraudiensi di kantor Adm. Jakarta Timur, Ketua Umum Ibu Hj.Chandra Manggih Rahayu didampingi Yuda Aji Bawono selaku Ketua Harian UKM IKM N, Bapak Rio, Bapak Warsito, Bapak Isnawan Pembina dan Ryan Dharmawan ketua kesekretariaytan. Audiensi di pimpin oleh Asisten Perekonomian & Pembangunan Kota Administrasi Jakarta Timur Drs. Syofian Thahir, Ibu Yeni Asnita Kepala Bagian Perekonomian serta jajarannya..'],
       ['Diskusi Kemitraan bersama Pertamina', 'nan', 'nan', 'Try',
        'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Audiensi di Kantor Walikota Jakarta Pusat', 'nan', 'nan', 'Try',
        'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Ketua Umum UKM IKM Nusantara menghadiri undangan kegiatan Orkestra dan BPJS di Bandung',
        'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Diskusi bersama Ketua Harian Nasional Bpk. Yuda A B dan para anggota UIN',
        'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Pameran Dekranasda Kabupaten Subang Jawa Barat', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Audiensi Walikota Jakarta Utara 27 Februari 2019', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kunjungan Kerja Kesekretariatan UIN', 'nan', 'nan', 'Try',
        'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kreatifitas dan inovatif dari anggota UKM IKM Nusantara', 'nan',
        'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Meeting Internal Pengurus UKM IKM Nusantara', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Ketua Umum UKM IKM Nusantara mengikuti jalan sehat di kegiatan rutin CFD di Jakarta',
        'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Semarak Jajanan Pasar Kota Solo 2019', 'nan', 'nan', 'Try',
        'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Meeting Rutin Korwil Jambi', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Diskusi bersama Gubernur Sulteng Bpk. longki Janggola', 'nan',
        'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['DPN meeting bersama President Indonesia Qatar Business', 'nan',
        'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagaram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Instagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Intagram', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['nan', 'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Konsolidasi Kepengurusan DPW Makassar', 'nan', 'nan',
        'Yudha Aji Bawono', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Ibu Ketua Umum Hj.Chandra Manggih Rahayu berkunjung kedaerah Makassar dengan tujuan bersilaturahmi dan mempererat struktural organisasi UKM IKM Nusantara khususnya kepengurusan DPW Makassar yang dimana Ketua Wilayah Makassar ini di jabat langsung oleh bpk. Kahar, background keseharian beliau ialah merupakan salah satu seorang Kontraktor dan Pengusaha Suplier ditanah air indonesia tercinta ini yang didampingi langsung oleh Ibu Idha selaku ketua harian di kepengurusan DPW Makassar ini, selain menjabat sebagai Ketua Harian di Struktural kepengurusan DPW Makassar, beliau juga berkeseharian sebagai Lawyer di kota Makassar sekaligus sebagai konsultan di PT. Vale.'],
       ['Sosialisasi di Kota Surakarta', 'nan', 'nan',
        'Yudha Aji Bawono', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Sosialisasi di Kota Surakarta', 'nan', 'nan',
        'Yudha Aji Bawono', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Tanggal 4 Januari 2019 tepatnya pada hari senin kemarin kepengurusan UKM IKM Nusantara berkolaborasi dengan Kementerian Dalam Negeri untuk mengadakan Sosialisasi bersama penduduk kota Surakarta yang tepatnya di selenggarakan di Hotel Lorin Solo Jawa Tengah.'],
       ['Kegiatan Forum Kemitraan Ormas UKM IKM Nusantara dan Kesbangpol Kemendagri di Surakarta Tahun 2019',
        'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Sosialisasi di Kota Surakarta\nTanggal 4 Januari 2019 tepatnya pada hari senin kemarin kepengurusan UKM IKM Nusantara berkolaborasi dengan Kementerian Dalam Negeri untuk mengadakan Sosialisasi bersama penduduk kota Surakarta yang tepatnya di selenggarakan di Hotel Lorin Solo Jawa Tengah.'],
       ['Kegiatan Forum Kemitraan Ormas UKM IKM Nusantara bersama Kesbangpol Kemendagri',
        'nan', 'nan', 'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kegiatan Forum Kemitraan Ormas UKM IKM Nusantara', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Paparan Ketua Harian Nasional Bpk. Yuda Aji Bawono tentara visi dan misi UKM IKM Nusantara'],
       ['Kegiatan Forum Kemitraan Ormas UKM IKM Nusantara', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kegiatan Forum Kemitraan Ormas UKM IKM Nusantara', 'nan', 'nan',
        'Try', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Sosialisasi di Kota Surakarta\nTanggal 4 Januari 2019 tepatnya pada hari senin kemarin kepengurusan UKM IKM Nusantara berkolaborasi dengan Kementerian Dalam Negeri untuk mengadakan Sosialisasi bersama penduduk kota Surakarta yang tepatnya di selenggarakan di Hotel Lorin Solo Jawa Tengah.'],
       ['Malam Tasyakuran',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-01-30-at-11_18_41/WhatsApp-Image-2019-01-30-at-11_18_41-2931618927.jpeg',
        'nan', 'Try', '30 Januari 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kolaborasi antara Pengurus Nasional & Ketua Wilayah Jambi',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-01-23-at-21_09_10/WhatsApp-Image-2019-01-23-at-21_09_10-1545858131.jpeg',
        'nan', 'Yudha Aji Bawono', '28 Januari 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Sosialisasi dengan Perkumpulan Pengusaha Muda Pekanbaru',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2019-01-24-at-15_18_13/WhatsApp-Image-2019-01-24-at-15_18_13-3922596533.jpeg',
        'nan', 'Yudha Aji Bawono', '28 Januari 2019',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'UKM IKM Nusantara tidak ada habis-habisnya mengadakan gebrakan untuk tercapai dan berjalanya program kerja 2019, yupp kali ini datang dari DPD UKM IKM Nusantara Prov. Riau'],
       ['UKM IKM Nusantara Bersinergi dengan Aspeparindo', 'nan', 'nan',
        'Yudha Aji Bawono', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Sedikit mengulas tentang pertemuan antara Ketua Umum UKM IKM Nusantara Ibu Chandra Manggih Rahayu yang didampingi langsung oleh Ketua HarianUKM IKM Nusantara Yuda Aji Bawonodengan Asosiasi Pengelola Parkir Indonesia atau biasa kita dengar sebagai Aspeparindo yang dihadiri oleh Irfan Yanuar selaku Ketua UmumAspeparindo dan Taufic Rachman SH, S.Sos selaku Sekertaris JendralAspeparindo beserta jajaran,'],
       ['RAPAT PLENO UKM IKM NUSANTARA (Pemantapan Kepengurusan Nasional UKM IKM Nusantara Periode 2019-2024)',
        'nan', 'nan', 'Yudha Aji Bawono', 'nan',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Hari Jum’at tepatnya pada tanggal 18 Januari 2019 disiang hari dengan cuaca sedikit agak mendung, ketua umum ibu Chandra Manggih Rahayu mengadakan Rapat Pleno di kantor kesekretariatan UKM IKM Nusantara yang dimana bertujuan untuk lebih memajukan Program kerja UKM IKM Nusantara di tahun 2019 kedepan ini.'],
       ['Lamongan fashion moslem festival 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-lamongan-jawa-timur/cmr-lamongan-jawa-timur-542304602.jpeg',
        'nan', 'Anna', '14 Desember 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['KESBANGPOL KEMENDAGRI bersama UKM IKM Nusantara Wilayah DI Jogjakarta',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/keg-di-jogja-afif-1des-2018-1/keg-di-jogja-afif-1des-2018-1-2840139122.jpeg',
        'nan', 'Anna', '14 Desember 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kegiatan UKM IKM Nusantara Wilayah Sumatera Selatan',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2018-12-13-at-20_59_15/WhatsApp-Image-2018-12-13-at-20_59_15-402738880.jpeg',
        'nan', 'Anna', '14 Desember 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Bincang santai dengan KASUM TNI Laksamana Madya Dr.Didit Herdiyawan Ashar',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-kasum-tni-bp-didit-des14-2/cmr-kasum-tni-bp-didit-des14-2-14945256.jpeg',
        'nan', 'Anna', '14 Desember 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Ibu Chandra Manggih Rahayu UKM IKM NUSANTARA mendapatkan kesempatan berbincang dan membahas rencana program kerja agar bisa berkolaborasi bersama KASUM TNI Laksamana Madya Dr.Didit Herdiyawan Ashar M.P.A, M.B.A di Cilangkap Jumat , December 14, 2018 sebagai usaha dari ibu Ketum untuk bisa melangkah, mewujudkan visi dan misi dari UKM IKM Nusantara serta usaha peningkatan usaha kerakyatan di berbagai berita , khususnya para pelaku UMKM diseluruh nusantara.\nPelaksanaan program serta rencana berkolaborasi yang di dukung penuh oleh Organisasi MOI (Media Online Indonesia) yang diketuai oleh Bp. Rudi Sembiring adalah diberita perikanan dan peternakan juga kelautan Pemberdayaan ekonomi kerakyatan, dimana media online memegang peranan yang sangat penting sebagai salah satu bentuk media promosi dan pemasaran yang harus di gencarkan dan disebarkan untuk kepentingan para pelaku . (by.DelyaFadriani)'],
       ['Silaturahmi dengan Bapak Mayjen Purn TNI Soedarmo Dirjen POLPUM KEMENDAGRI',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2018-12-04-at-18_56_09/WhatsApp-Image-2018-12-04-at-18_56_09-4226667382.jpeg',
        'nan', 'Anna', '5 Desember 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Silaturahmi dengan Bapak Budi Prasetyo KEMENDAGRI',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-budi-prasetya-staff-ahli-kemendagri-Nov28/cmr-budi-prasetya-staff-ahli-kemendagri-Nov28-2198734531.jpeg',
        'nan', 'Anna', '30 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Meeting santai bersama RKIH ibu Linda Kartika',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/20180927_155829/20180927_155829-3943755376.jpg',
        'nan', 'Anna', '28 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Bapak Anwar Sanusi Sekertaris Jenderal Kementerian Desa PDTT bersinergi dengan UKM IKM Nusantara',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/kemendes-anwar-sanusi-2-28sep2018/kemendes-anwar-sanusi-2-28sep2018-3397030564.jpeg',
        'nan', 'Anna', '28 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Bersama dengan Bapak Poempida H. Ketua Umum ORKESTRA',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-poempida-anthony-fernando/cmr-poempida-anthony-fernando-1948269726.jpeg',
        'nan', 'Anna', '28 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Kegiatan Forum Komunikasi dan Koordinasi Nasional dan Regional antara Pemerintah Pusat, Pemerintah Daerah dan Ormas – KEMENDAGRI',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-MENTERI-DALAM-NEGERI-hotel-REDTOP-2/cmr-MENTERI-DALAM-NEGERI-hotel-REDTOP-2-3411595692.jpeg',
        'nan', 'Anna', '28 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Bincang santai Ibu Ketua Umum dengan Bapak Dirjen Harry Hikmat.',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cmr-dirjen-HH-Kemensos/cmr-dirjen-HH-Kemensos-40321994.jpeg',
        'nan', 'Anna', '28 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['FUN RUN UKM IKM Nusantara di CFD Rawamangun Jaktim',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/cfd-ketum-walkotim-2/cfd-ketum-walkotim-2-1088478624.jpeg',
        'nan', 'Anna', '27 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['AUDIENSI UKM IKM NUSANTARA DENGAN KEMENTERIAN SOSIAL DIREKTORAT JENDERAL PENANGANAN FAKIR MISKIN',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2018-11-21-at-19_39_29/WhatsApp-Image-2018-11-21-at-19_39_29-1879015298.jpeg',
        'nan', 'Anna', '23 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['KEGIATAN SOSIALISASI KEMASAN DAN MERK BERSAMA DENGAN KEMENTERIAN PERINDUSTRIAN',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/uin-sosialisasi-konsultasi-design-kemasan-kemenperind/uin-sosialisasi-konsultasi-design-kemasan-kemenperind-1999614321.jpeg',
        'nan', 'Anna', '23 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['RAPAT BERSAMA PEMBAHASAN KONSEP TENANT UMK REST AREA TOL BREXIT (Jawa Tengah)',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/WhatsApp-Image-2018-11-21-at-23_21_38/WhatsApp-Image-2018-11-21-at-23_21_38-35350112.jpeg',
        'nan', 'Anna', '23 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Hari/tanggal : Rabu, 21 november 2018'],
       ['Rapat Bersama KEMENSOS untuk Kegiatan Kewirausahaan Sosial – Ditjen Pemberdayaan Sosial',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/uin-kemensos-Ditjen-DAYASOS-2/uin-kemensos-Ditjen-DAYASOS-2-3600344507.jpeg',
        'nan', 'Anna', '23 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['Silaturahmi bersama Dirjen Pemberdayaan Sosial – Kementerian Sosial R.I',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/IMG-20181105-WA0016/IMG-20181105-WA0016-3972533040.jpg',
        'nan', 'Anna', '23 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Kegiatan UKM IKM Nusantara bersama Dirjen Pemberdayaan Sosial – Kementerian Sosial.'],
       ['PERTEMUAN DENGAN IBU DIREKTUR SMESCO',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/IMG-20181111-WA0061/IMG-20181111-WA0061-2792921874.jpg',
        'nan', 'Subiyantoro', '15 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'nan'],
       ['KEGIATAN ORGANISASI UKM IKM NUSANTARA',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/IMG-20181111-WA0057/IMG-20181111-WA0057-1503309392.jpg',
        'nan', 'Subiyantoro', '15 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'Tanggal : 09 November 2018'],
       ['“RUN FUN” oleh UKM IKM Nusantara di CFD Jakarta Timur 25 November 2018!',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/IMG-20181110-WA0008/IMG-20181110-WA0008-1943413339.jpg',
        'nan', 'Yudha Aji Bawono', '14 November 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        'RUN FUN'],
       ['UKM IKM Nusantara & Organisasi Kesejahteraan Rakyat (Orkestra)',
        'https://ukmikmnusantara.com/wp-content/uploads/cache/images/DSC_0057/DSC_0057-3938068535.jpg',
        'nan', 'Yudha Aji Bawono', '4 Oktober 2018',
        'https://ukmikmnusantara.com/wp-content/uploads/DSC_0057.jpg',
        '30 September 2018 – UKM IKM Nusantara akan selalu mencari segala kesempatan untuk berkolaborasi ke organisasi masyarakat lainnya. Kali ini UIN berkerja sama dengan Organisasi Kesejahteraan Rakyat (Orkestra) yang akan membuat gerakan – gerakan visioner untuk memberikan kemudahan – kemudahan kepada anggota UIN dan Orkestra.Bersama dengan Poempida Hidayatulloh sebagai Ketua Umum Orkestra, Ibu Chandra Manggih akan menggali segala potensi – potensi yang bisa di kembangkan bersama. Potensi tersebut salah satunya adalah pencarian dana CSR yang terdapat di beberapa kementerian dan perusahaan bumn yang nantinya akan digunakan untuk membantu pelaku UKM dan IKM dalam berita permodalan. Karena permodalan adalah salah satu dari hambatan umum jika ingin berbisnis. Tetapi untuk mendapatkan dana CSR tersebut bukan hal yang mudah, oleh karena itu UIN dan Orkestra menyatukan pikiran dan tujuan untuk mendapatkan dana tersebut. Dalam acara kali ini di Menara Jamsostek, Orkestra menyelenggarakan Rakernas untuk membahas regulasi – regulasi untuk menjaga utuh kesatuan Orkestra dalam hal berorganisasi. UKM IKM Nusantara akan melaksanakan Rakernas di awal tahun 2019 yang berlokasi di Bandung, Jawa Barat. Karena Rakernas adalah sebuah kegiatan satu tahun sekali yang biasanya dilakukan oleh sebuah organisasi masyarakat untuk mengevaluasi hal – hal yang telah terjadi selama 1 tahun']];

        for ($i = 0; $i < count($berita); $i++) {
            DB::table('beritas')->insert([
                'judul' => $berita[$i][0],
                'gambar' => $berita[$i][1],
                'author' => $berita[$i][3],
                'tanggal' => $berita[$i][4],
                'konten' => $berita[$i][6]
            ]);
        }
    }
}
