export const IS_LOGIN = "IS_LOGIN";
export const IS_REGISTERED = "IS_REGISTERED";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_PENDING = "REQUEST_LOGIN_PENDING";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_ERROR = "REQUEST_LOGIN_ERROR";
export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const FETCH_USER_DATA = "FETCH_USER_DATA";